### ISSUE TITLE
date_utils import problem when lint-staged is run

### ISSUE THREAD

**Issue by ELI7VH** [frappe/gantt#184]
Cannot use import statement outside a module

```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import date_utils from './date_utils';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React, { useState, useEffect, useRef } from 'react'
    > 2 | import Gantt from 'frappe-gantt'
        | ^
      3 | 
      4 | export const GanttView = () => {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/components/JobScheduling/GanttView/index.tsx:2:1)

```

any idea how to fix this. It won't pass our linting.

our app compiles and runs... but we can't commit this library because of this error

**Comment by ELI7VH** [comment]
this package requires this key-value in your `package.json:jest:moduleNameMapper` object:
```
"frappe-gant": "frappe-gantt/dist/frappe-gantt.js"
```
